---
title: "Lab04_ReinKatherine"
output: html_document
date: "2024-02-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A1/A3 - Sustainable Yield Curve

```{r}
# Calculate the growth rate for a vector of N's
log_growth_rate <- function(r,N,K){
  dNdt = r*N*(1-(N/K))
  return(dNdt)
}

# Set Initial Conditions
r = 0.6 # units: fish per year
K = 3200 # units: tonnes
N = 0:K

# Calculate dNdt and graph
dNdt = log_growth_rate(r,N,K)
plot(N,dNdt, type = "l", lwd = 2, ylim = range(dNdt), xlim = range(N), col = "black", main = "Sustainable Yield Curve", xlab = "Population Size (tonnes)", ylab = "Growth Rate (tonnes of fish/year)")

# Add MSY Point
points(equil_stock_size,msy, pch = 16, col = "red", lwd = 5)

legend("topleft", legend = c("SYC","MSY"), col = c("black","red"), lty = c(1, NA), pch = c(NA, 16), lwd = c(2,5))

```

## A2 - Maximum Sustainable Yield

```{r}
# Set Initial Conditions
r = 0.6 # units: fish per year
K = 3200 # units: tonnes

# Calculate MSY and equilibrium stock size
msy = (r*K)/4
msy
equil_stock_size = K/2
equil_stock_size

```

## B1 - 18% Graph

```{r}
# Set Initial Conditions
r = 0.6 # units: fish per year
K = 3200 # units: tonnes
N = 1:K
N_18 = N

# Calculate dNdt and 18%
dNdt = log_growth_rate(r,N,K)

for(t in 1:N){
    N_18[t+1] = N[t] + r*N[t]*(1-N[t]/K) - 0.18
  } 

# Graph
plot(N,dNdt, type = "l", lwd = 2, ylim = range(dNdt), xlim = range(N), col = "black", main = "Sustainable Yield Curve", xlab = "Population Size (tonnes)", ylab = "Growth Rate (tonnes of fish/year)")
lines(N,N_18, lwd = 2, lty = 2, ylim = range(dNdt), xlim = range(N), col = "red")
legend("topright", legend = c("SYC","18% SYC"), col = c("black","red"), lty = c(1, 2), lwd = c(2,2))
```

## B2 - Estimate Harvest and Stock Limits

I'm not sure how to do this

## B3 - Total Harvest

```{r}

```

## C1 - Liscensed Vessels Graph

```{r}
license_limits <- function(alpha,E,N){
  for(i in 1:length(E)){
    H = alpha*E[i]*N
    lines(N, H, col = i+1) # color will change with i
  } 
}

# Set Initial Conditions
r = 0.6 # units: fish per year
K = 3200 # units: tonnes
N = 0:K
alpha = 0.001
E = c(50,100,200,500) # number of liscensed vessels

# Initial Graph
plot(N,dNdt, type = "l", lwd = 2, ylim = range(dNdt), xlim = range(N), col = "black", main = "Sustainable Yield Curve", xlab = "Population Size (tonnes)", ylab = "Growth Rate (tonnes of fish/year)")

# Add License Limits Lines
license_limits(alpha,E,N)
legend("bottomright", title = "Licensed Vessels", legend = E,
         col = 2:(length(E) + 1), lty = 1)

```

## C2 - Per Vessel Harvest



## C3 - Effort Yield Curve

```{r}
# Initial Conditions
r = 0.6 # units: fish per year
K = 3200 # units: tonnes
N = 0:K
alpha = 0.001

# Define E and H and then graph
Effort_Yield_Curve <- function(r,K,N,alpha){
  E = (r/alpha)*(1 - (N/K))
  H = alpha*E*N
  
  # Plot the effort vs harvest vectors
  plot(E, H, type = "l", lwd = 2, ylim = range(H), xlim = range(E), col =
         "black", main = "Effort Yield Curve", xlab = "Effort", ylab =
         "Harvest")
}

# Call Curve function
Effort_Yield_Curve(r,K,N,alpha)

```




