---
title: "Lab03_ReinKatherine"
output: html_document
date: "2024-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A1 - Continuous Growth (10 weeks)

```{r}
# Define a continuous exponential growth function
con_exp_growth <- function(N_initial, r, NT){
  t_cont = 0:NT
  N = N_initial * exp(r*t_cont)
  return(N)
}

# Set initial conditions
r = 0.4
N_initial = 38
NT = 10

# Call function and graph
N = con_exp_growth(N_initial, r, NT)
plot(0:NT, N, type = 'l', main = "Continuous Exponential Growth Function", xlab = "Time", ylab = "Population Size", col = "DarkBlue")
```

## A2 - Discrete Growth

```{r}
# Define a discrete exponential growth function
dis_exp_growth <- function(N_initial, r, NT){
  R = exp(r)
  t_dis = 0:NT
  N = rep(N_initial,NT+1)
  
  for(t in 1:NT){
    N[t+1] = R*N[t]
  }
  return(N)
}

# Set initial conditions
r = 0.4
N_initial = 38
NT = 10

# Call function and graph
N = dis_exp_growth(N_initial, r, NT)
plot(0:NT, N, type = 'l', main = "Discrete Exponential Growth Function", xlab = "Time", ylab = "Population Size", col = "DarkBlue")
```

## A3 - Doubling Time

```{r}
# Define a doubling time function
doubling_time <- function(r){
  double_time = (exp(2))/r
  return(double_time)
}

# Set initial conditions
r = 0.4

# Call function and output answer
double_time = doubling_time(r)
rounded_double_time = round(double_time,2)
print(paste("The doubling time according to both the discrete and continuous functions is", rounded_double_time))
```

## A4 - Both Curves One Graph

```{r}
# Set initial conditions
r = 0.4
N_initial = 38
NT = 10

# Call functions
N_con = con_exp_growth(N_initial, r, NT)
N_dis = dis_exp_growth(N_initial, r, NT)

# Graph both functions
plot(0:NT, N_con, type = 'l', main = "Exponential Growth Functions", xlab = "Time", ylab = "Population Size", col = "DarkBlue", lwd = 2)
lines(0:NT, N_dis, type = 'l', main = "Exponential Growth Functions", xlab = "Time", ylab = "Population Size", col = "Red", lty = 4, lwd = 2)
legend("topleft", legend = c("Continuous","Discrete"), col = c("DarkBlue","Red"), lty = c(1,4), lwd = c(2,2))
```

## A5 - Sensitivity Analysis

```{r}
# Initial Conditions
i = 20
NT = 10
r = runif(i, -1, 1)
N_initial = sample(1:100, i, replace = TRUE)

# Create Vectors
N_ten = rep(0,NT)
r_ten = rep(0,NT)
N_initial_ten = rep(0,NT)

# Find the 10th value for each set of conditions
for(x in 0:i){
  N = con_exp_growth(N_initial[x], r[x], NT)
  N_ten[x] = N[10]
  r_ten[x] = r[x]
  N_initial_ten = N_initial[x]
}

# Log Data
log_N_ten = log10(N_ten)

# Plot Data
plot(r_ten, log_N_ten, type = 'p', xlim = range(r_ten), ylim = range(log_N_ten), main = "Sensitivity of r", xlab = "r", ylab = "Population Size", col = "DarkBlue", lwd = 1)

plot(N_initial_ten, log_N_ten, type = 'p', xlim = range(N_initial_ten), ylim = range(log_N_ten), main = "Sensitivity of Initial Population Size", xlab = "Initial Population Size", ylab = "Population Size", col = "DarkBlue", lwd = 1)

```

## B1 - Discrete Logistic Growth

```{r}
# Define a discrete logistic growth function
dis_log_growth <- function(N_initial, r, NT, K){
  t_dis = 0:NT
  N = rep(N_initial,NT+1)
  
  for(t in 1:(NT-1)){
    N[t+1] = N[t] + r*N[t]*(1-N[t]/K)
  }
  return(N)
}

# Set initial conditions
r = 0.3
N_initial = 2
NT = 52
K = 250

# Call function and graph
N = dis_log_growth(N_initial, r, NT, K)
plot(0:NT, N, type = 'l', main = "Discrete Logistic Growth Function", xlab = "Time", ylab = "Population Size", col = "DarkBlue")
```

## B2 - Carrying Capacity

```{r}
# Define a function to break once K is surpassed
find_K <- function(N,K){
  K = K-0.5
  
  for(x in 1:length(N)){
    if(N[x]>K){
      return(x)
    }
  }
}

# Set initial conditions
r = 0.3
N_initial = 2
NT = 52
K = 250

# Call function
N = dis_log_growth(N_initial, r, NT, K)
weeks_K = find_K(N,K)
weeks_K
```

## B3 - Max Growth Rate/Population

```{r}
# Define a function to find the Max Growth Rate
max_growth_rate <- function(K){
  return(K/2)
}

# Define a function to find the Population Size at MGR
pop_size_MGR <- function(r,K){
  return((r*K)/4)
}

# Set initial conditions
K = 250

# Call function
MGR = max_growth_rate(K)
MGR

pop_size = pop_size_MGR(MGR,K)
pop_size

```

