---
title: "ReinKatherine_Exam2TakeHome"
output: html_document
date: "2024-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Units

tot_energyconsump = quad Btu
energyconsump_percap = MMBtu/person
energyintensity = 1000 Btu/2015$ GDP PPP
GDP = Billion 2015$ PPP
CO2 = MMtonnes CO2
pop = Mperson


## Import Packages

```{r}
install.packages("readxl", repos = "http://cran.us.r-project.org")
install.packages("plotrix", repos = "http://cran.us.r-project.org")
library("readxl")
library(plotrix)
```


## Import Data

```{r}
# Read in the files
data_tot_energyconsump <- read_excel("exam2data_fall22.xlsx", sheet = "total energy consumption", na = "--")
data_energyconsump_percap <- read_excel("exam2data_fall22.xlsx", sheet = "energy consumption per capita", na = "--")
data_energyintensity <- read_excel("exam2data_fall22.xlsx", sheet = "Energy$(Energy intensity)", na = "--")
data_GDP <- read_excel("exam2data_fall22.xlsx", sheet = "GDP", na = "--")
data_CO2 <- read_excel("exam2data_fall22.xlsx", sheet = "CO2emissions", na = "--")
data_pop <- read_excel("exam2data_fall22.xlsx", sheet = "population", na = "--")
```

## Cleaning Data

```{r}
# Select 2015 from each sheet and add to a new data frame
data = data.frame(matrix(nrow=231,ncol=0))
data$tot_energyconsump = data_tot_energyconsump$"2015"
data$energyconsump_percap = data_energyconsump_percap$"2015"
data$energyintensity = data_energyintensity$"2015"
data$GDP = data_GDP$"2015"
data$CO2 = data_CO2$"2015"
data$pop = data_pop$"2015"

# Set Row Names
row.names(data) <- data_pop$...2

# Remove World row
data = data[-1, ]

# Replace more NAs
data[data == 0] <- NA
data[data == "NA"] <- NA

# Create a Row Names vector

RowNames = row.names(data)

# Make sure values are numeric
data$energyconsump_percap = as.numeric(data$energyconsump_percap)
data$energyintensity = as.numeric(data$energyintensity)
data$GDP = as.numeric(data$GDP)
data$pop = as.numeric(data$pop)
```


## Calculate New Variables

```{r}
# Per capita income (GDP/person)
# Multiply GDP by 1B as it's given in billions
# Multiply pop by 1M as it's given in millions
data$pc_income = (data$GDP * 1000000000) / (data$pop * 1000000)

# Energy Intensity (BTU/$ GDP)
# Divide by 1000 to remove 1000 BTU
data$energyintensity = data$energyintensity / 1000

# Carbon Intensity (CO2/BTU)
# Currently in units of MMtonnes CO2 / quad Btu
data$carbonintensity = data$CO2 / data$tot_energyconsump
```

## Check for Colinearity

```{r}
# Create pairs plot and correlation values
pairs(data)
cor(data, use = "pairwise.complete.obs")
```

## Create Scatter Plots

```{r}
# EKC plot
row.names(data) <- 1:230
zoomed.data <- data[data$CO2 < 400,]
plot(zoomed.data$pc_income, zoomed.data$CO2, xlab = "Per Capita Income ($)", ylab = "CO2 (MMtonnes)", main = "EKC Correlation")
abline(a = 0, b = 1, col = "red")
legend("topright", legend = "1:1 Line", col = "red", lty = 1)

# Reset row names
row.names(data) <- RowNames

# Remove NAs
data = na.omit(data[])
```

# Total Emissions Models

```{r}
# Model including only total emissions and per capita income (EKC)
# added in quadratic using https://www.spsanderson.com/steveondata/posts/2023-11-17/index.html
# add in quadratic by squaring the pc_income column
data$pc_income_sq = -(data$pc_income^2)

fit_totem_pcinc_EKC = lm(CO2 ~ pc_income + pc_income_sq, data)
summary(fit_totem_pcinc_EKC)
our_aic = AIC(fit_totem_pcinc_EKC)
print(our_aic)

plot(predict(fit_totem_pcinc_EKC),data$CO2, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Total Emissions (EKC)")
abline(a = 0, b = 1, col = "red")
legend("topright", legend = "1:1 Line", col = "red", lty = 1)

# Linear Model
fit_totem_pcinc = lm(CO2 ~ pc_income, data)
summary(fit_totem_pcinc)
our_aic = AIC(fit_totem_pcinc)
print(our_aic)

plot(predict(fit_totem_pcinc),data$CO2, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Total Emissions (Linear Model)")
abline(a = 0, b = 1, col = "red")

# Polynomial Model
fit_totem_poly = lm(CO2 ~ I(pc_income) + I(pc_income^2) + I(pc_income^3), data)
summary(fit_totem_poly)
our_aic = AIC(fit_totem_poly)
print(our_aic)

plot(predict(fit_totem_poly),data$CO2, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Total Emissions (Polynomial Model)")
abline(a = 0, b = 1, col = "red")

# IPAT
fit_IPAT = lm(CO2 ~ pop * pc_income * carbonintensity, data)
summary(fit_IPAT)
our_aic = AIC(fit_IPAT)
print(our_aic)

plot(predict(fit_IPAT),data$CO2, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Total Emissions (IPAT Model)")
abline(a = 0, b = 1, col = "red")
legend("topright", legend = "1:1 Line", col = "red", lty = 1)

```

# Energy Intensity Models

```{r}
# Model including only total emissions and per capita income (EKC)
# added in quadratic using https://www.spsanderson.com/steveondata/posts/2023-11-17/index.html
fit_ei_pcinc_EKC = lm(energyintensity ~ pc_income_sq, data)
summary(fit_ei_pcinc_EKC)
our_aic = AIC(fit_ei_pcinc_EKC)
print(our_aic)

plot(predict(fit_ei_pcinc_EKC),data$energyintensity, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Energy Intensity (EKC)")
abline(a = 0, b = 1, col = "red")

# Linear Model
fit_ei_pcinc = lm(energyintensity ~ pc_income, data)
summary(fit_ei_pcinc)
our_aic = AIC(fit_ei_pcinc)
print(our_aic)

plot(predict(fit_ei_pcinc),data$energyintensity, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Energy Intensity (Linear Model)")
abline(a = 0, b = 1, col = "red")

# Polynomial Model
fit_ei_poly = lm(energyintensity ~ I(pc_income) + I(pc_income^2) + I(pc_income^3), data)
summary(fit_ei_poly)
our_aic = AIC(fit_ei_poly)
print(our_aic)

plot(predict(fit_ei_poly),data$energyintensity, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Energy Intensity (Polynomial Model)")
abline(a = 0, b = 1, col = "red")
```

# Carbon Intensity Models

```{r}
# Model including only total emissions and per capita income (EKC)
# added in quadratic using https://www.spsanderson.com/steveondata/posts/2023-11-17/index.html
fit_ci_pcinc_EKC = lm(carbonintensity ~ pc_income_sq, data)
summary(fit_ci_pcinc_EKC)
our_aic = AIC(fit_ci_pcinc_EKC)
print(our_aic)

plot(predict(fit_ci_pcinc_EKC),data$carbonintensity, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Carbon Intensity (EKC)")
abline(a = 0, b = 1, col = "red")

# Linear Model
fit_ci_pcinc = lm(carbonintensity ~ pc_income, data)
summary(fit_ci_pcinc)
our_aic = AIC(fit_ci_pcinc)
print(our_aic)

plot(predict(fit_ci_pcinc),data$carbonintensity, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Carbon Intensity (Linear Model)")
abline(a = 0, b = 1, col = "red")

# Polynomial Model
fit_ci_poly = lm(carbonintensity ~ I(pc_income) + I(pc_income^2) + I(pc_income^3), data)
summary(fit_ci_poly)
our_aic = AIC(fit_ci_poly)
print(our_aic)

plot(predict(fit_ci_poly),data$carbonintensity, pch = 19, cex = 0.7, xlab = "Predicted Values", ylab = "Observed Values", main = "Observed vs. Predicted Carbon Intensity (Polynomial Model)")
abline(a = 0, b = 1, col = "red")
```



